### ISSUE TITLE
[bug] How to support CJK fonts?

### ISSUE THREAD

**Issue by niheaven** [dreamRs/gfonts#6]
e.g. Noto Sans SC

Thanks.

**Comment by pvictor** [comment]
Hello,

What have you tried ?

This works fine for me:

```r
library(shiny)
library(gfonts)
setup_font(
  id = "noto-sans-sc",
  output_dir = "path/to/www/"
)

# Shiny app
ui <- fluidPage(
  use_font("noto-sans-sc", "www/css/noto-sans-sc.css"),
  tags$h1("Noto Sans SC"),
  tag_example()
)

server <- function(input, output, session) {

}

shinyApp(ui, server)
```

Victor

**Comment by niheaven** [comment]
Not for CJK...

Since Noto Sans likes default font, let's try [Ma Shan Zheng](https://fonts.google.com/specimen/Ma+Shan+Zheng?subset=chinese-simplified)
![image](https://user-images.githubusercontent.com/5832170/99145386-63c33c80-26a9-11eb-8109-232201b983eb.png)

```r
library(shiny)
library(gfonts)
setup_font(
  id = "ma-shan-zheng",
  output_dir = "www"
)

# Shiny app
ui <- fluidPage(
  use_font("ma-shan-zheng", "www/css/ma-shan-zheng.css"),
  tags$h1("中文测试 Ma Shan Zheng"),
  tag_example()
)
server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

Look, ASCII's okay, but CJK or Unicode went wrong.

![image](https://user-images.githubusercontent.com/5832170/99145405-93724480-26a9-11eb-8add-4049c46b323a.png)

**Comment by niheaven** [comment]
Not for CJK...

Since Noto Sans likes default font, let's try [Ma Shan Zheng](https://fonts.google.com/specimen/Ma+Shan+Zheng?subset=chinese-simplified)
![image](https://user-images.githubusercontent.com/5832170/99145386-63c33c80-26a9-11eb-8109-232201b983eb.png)

```r
library(shiny)
library(gfonts)
setup_font(
  id = "ma-shan-zheng",
  output_dir = "www"
)

# Shiny app
ui <- fluidPage(
  use_font("ma-shan-zheng", "www/css/ma-shan-zheng.css"),
  tags$h1("中文测试 Ma Shan Zheng"),
  tag_example()
)
server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/5832170/99145405-93724480-26a9-11eb-8add-4049c46b323a.png)

**Comment by pvictor** [comment]
Thanks, I see the problem. Subsets are ignored and default is latin, chinese-simplified is ignored.

Two solutions for you:
* One with current CRAN version and some manual adjustments
* One with GitHub version (if you can test this one too please, if it works for you, I'll submit to CRAN)

## Current CRAN version

You cannot use `setup_font` but still can download it and use it:

```r
# download the font:
download_font(
  id = "ma-shan-zheng",
  output_dir = "www/fonts/",
  subsets = "latin,chinese-simplified"
)
```

After that you have to create appropriate CSS manually:

```css
/* ma-shan-zheng-regular - latin_chinese-simplified */
@font-face {
  font-family: 'Ma Shan Zheng';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.eot'); /* IE9 Compat Modes */
  src: local('Ma Shan Zheng Regular'), local('MaShanZheng-Regular'),
       url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/ma-shan-zheng-v5-latin_chinese-simplified-regular.svg#MaShanZheng') format('svg'); /* Legacy iOS */
}
```
From : https://google-webfonts-helper.herokuapp.com/fonts/ma-shan-zheng?subsets=chinese-simplified,latin

## GitHub version

First re-install from GitHub:

```r
devtools::install_github("dreamRs/gfonts")
```

Then use `setup_font`:

```r
setup_font(
  id = "ma-shan-zheng",
  output_dir = "www/",
  subsets = "latin,chinese-simplified"
)
```

Both methods should render:

![image](https://user-images.githubusercontent.com/4415580/99146503-14651800-2679-11eb-9ee6-83d3873786d0.png)


Let me know how it works for you.

Victor
